mfdw_root/blog/urls.py
from . import views
from django.urls import path
from .views import AboutPageView # new

app_name = 'blog'
urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    #path('about/', AboutPageView.as_view(), name = 'about'),
    #path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('<slug:slug>/', views.post_detail, name='post_detail')
]

mfdw_root/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]


mfdw_root/blog/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    email = models.EmailField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)


# Create your models here.

mfdw_root/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    # function for counting number of total votes
    

mfdw_root/blog/forms.py
#Form to display all comments in post_detail page


from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email', 'body')

mfdw_root/blog/views.py
from django.views import generic
from .models import Post
from .forms import CommentForm
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/index.html'

class HomeView(TemplateView):
    template_name = 'blog/home.html'


class AboutPageView(TemplateView):
    template_name = 'blog/about.html'


def post_detail(request, slug):
    template_name = 'blog/post_detail.html'
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})

mfdw_root/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

    """
    Return the last five published questions (not including those set to be
    published in the future).
    """


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mfdw_root/blog/templates/blog/about.html
{% extends "blog/base.html" %} 


{% block content %}


<h1>About page</h1>
<p> This is the about page.
The homepage needs to include fight card information as main content.
News/tweets come up as widget on left-hand side.
Most recent poll and blog post show up on right-hand side. </p>

<h2> Next Steps </h2>
<p> 1. Include poll and blog content on homepage (right of main content). &check;</p>
<p> 2. Produce a bar chart for poll votes based on percentages. </p>
<p> 3. Inlcude selceted tweets/articles on left hand side home page. </p>
<p> 4. Include fight card information on main content (via web scraping). </p>
<p> 5. Improve design and layout of the entire site. </p>


{%endblock content%}

mfdw_root/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Warmongers</title>

    <link
      href="https://fonts.googleapis.com/css?family=Roboto:400,700"
      rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    
  </head>

  <body>
    <style>
      body {
        font-family: "Roboto", sans-serif;
        font-size: 17px;
        background-color: #fdfdfd;
      }

    .shadow{
           box-shadow: 0 4px 2px -2px rgba(0,0,0,0.1);
       }
      .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
      }
     
     .masthead {
              background:#707070;
              height: auto;
              padding-bottom: 15px;
              box-shadow: 0 16px 48px #E3E7EB;
              padding-top: 10px;
    }
    </style>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home1' %}" >WARMONGERS</a>
        <button
          class="navbar-toggler navbar-toggler-right"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
       
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            
            <li class="nav-item text-black">
              <a
                class="nav-link text-black font-weight-bold"
                href="/blog"
                >Blog</a
              >
            </li>
            <li class="nav-item text-black">
              <a
                class="nav-link text-black font-weight-bold"
                href="#"
                >Sims</a
              >
              <li class="nav-item text-black">
            </li>
            <li class="nav-item text-black">
              <a
                class="nav-link text-black font-weight-bold"
                href="/polls"
                >Polls</a
              >
              <li class="nav-item text-black">
            </li>
            <a
                class="nav-link text-black font-weight-bold"
                href="/about"
                >About</a
              >
          </ul>
        </div>
      </div>
    </div>
    </nav>
    
     {% block content %}
        <!-- Content Goes here -->
     {% endblock content %}
    
    
  </body>
</html>

mfdw_root/blog/templates/blog/home.html
{% extends "blog/base.html" %} 

{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to Warmongers! </h3>
                    <p class="text-light">This is your one stop shop for upcoming UFC cards - the latest news, fan discussions, polls and most of all the fight simulator! 
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Try Static input here -->
 {% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/style1.css' %}">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

}

/* Change color on hover */
.topnav a:hover {
  background-color: #ddd;
  color: black;
}

/* Create three unequal columns that floats next to each other */
.column {
  float: left;
  padding: 30px;
}

/* Left and right column */
.column.side {
  width: 25%;
}

/* Middle column */
.column.middle {
  width: 50%;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .column.side, .column.middle {
    width: 100%;
  }
}
</style>
</head>
<body>
<!-- 
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style1.css' %}"> -->

<div class="row">
  <div class="column side">
    <h2>News</h2>
    <p>Rolling news articles and tweets</p>
  </div>
  
  <div class="column middle">
    <h2>Main Content</h2>
    <p> This is where the UFC card fight details will be!</p>
  </div>
  
  <div class="column side">

    {% block sidebar %} {% include 'blog/sidebar-blog.html' %} {% endblock sidebar %}
    {% block sidebar1 %} {% include 'blog/sidebar-polls.html' %} {% endblock sidebar1 %}

  </div>
 

</div>

  
</body>
</html>




{% endblock content %}

mfdw_root/blog/templates/blog/index.html
{% extends "blog/base.html" %} 

{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<div class="container">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":201" }}...</p>
                    <a href="{% url 'blog:post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        
    </div>
</div>

{%endblock content%}

mfdw_root/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
  
  </div>
</div>


<div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ comments.count }} comments</h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

mfdw_root/blog/templates/blog/sidebar-blog.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-10 float-right ">
<div class="card my-9">
        <h5 class="card-header">Blogs</h5>
    <div class="card-body">
        <a href="blog/intro-2" class="card-link">Intro 2</a><br><br>
        <a href="blog/introduction" class="card-link">Introduction..</a><br><br>
        <a href="blog/"
           class="btn btn-dark">See more!</a>
    </div>
</div>
</div>

<!-- Needs to be cleverer: The two most recent posts update automatically to redirect user to the appropriate blog -->


{% endblock sidebar %}

mfdw_root/blog/templates/blog/sidebar-polls.html
{% block sidebar1 %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-10 float-right ">
<div class="card my-8">
        <h5 class="card-header">Polls</h5>
    <div class="card-body">
        <a href="polls/4" class="card-link">Jake Paul vs Ben Askren</a><br><br>
        <a href="polls/3" class="card-link">Zhang Weili vs Rose Namajunas..</a><br><br>
        <a href="polls/"
           class="btn btn-dark">See more!</a>
    </div>
</div>
</div>



{% endblock sidebar1 %}

mfdw_root/blog/templates/blog/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-10 float-right ">
<div class="card my-9">
        <h5 class="card-header">Blogs</h5>
    <div class="card-body">
        <p class="card-text"> Blog posts.. </p>
        <a href="blog/"
           class="btn btn-danger">See more!</a>
    </div>
</div>
</div>




{% endblock sidebar %}

mfdw_root/polls/templates/polls/detail.html
{% extends "blog/base.html" %} 

{% block content %}

<!-- Section that imports static css files -->
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">


<h1>{{ question.question_text }}</h1>
<p> Who will win? </p>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token  %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>


{% endblock content %}

mfdw_root/polls/templates/polls/index.html

{% extends "blog/base.html" %} 

{% block content %}


<!-- Section that imports static css files -->
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">


<!-- HTML script -->
<body>
	{% if latest_question_list %}
    	<ul>
    	{% for question in latest_question_list %}
        <li id="item1"><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    	{% endfor %}
    	</ul>
	{% else %}
    	<p>No polls are available.</p>
	{% endif %}
</body>


{% endblock content %}

mfdw_root/polls/templates/polls/results.html
{% extends "blog/base.html" %} 

{% block content %}

<!-- Section that imports static css files -->
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    <p> {{ choice.votes }} </p> 
{% endfor %}
</ul>

<p> Print total votes here somehow???? </p>
<p> Need to create a horizontal bar chart along with percentages </p>





<a href="{% url 'polls:index' %}">Vote for another fight?</a>


{%endblock content%}